version: '3'
services:
  mysql:
    platform: linux/x86_64

    image: mysql:8.0
    container_name: mysql_container
    ports:
      - '3306:3306'

    environment:
      MYSQL_ROOT_PASSWORD: 'admin'

      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'sns'
