version: '3'
services:
  webserver:
    image: ubuntu
    build: .

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_HOST: 'localhost'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'sns'
      TZ: Asia/Seoul
