# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    # node_mocules를 검사해서 cache 확인
    - name: Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: npm-packages-${{ hashFiles('**/package-lock.json') }}
          
      # npm ci는 npm install과 같은 기능을 수행
      - run: npm ci
      
      # --if-present은 npm 스크립트가 존재할 때만 실행시킴
      # 만약 build 스크립트가 없는 경우, 오류 없이 지나간다.
      - run: npm run build --if-present
      - run: npm test
    
#     - name: Use Docker-compose
#       run: docker-compose up
      
#     - name: Build
#       run: npm run start:dev

