# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    # node_mocules를 검사해서 cache 확인
    - name: Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: npm-packages-${{ hashFiles('**/package-lock.json') }}
          
    # cache 검사에서 모듈변화가 있다면 npm install
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    
    - name: Test unit
      run: npm test
    
#     - name: Use Docker-compose
#       run: docker-compose up
      
    - name: Build
      run: npm run start:dev

